version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -cors * -inMemory"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    network_mode: host
    ports:
      - "8000:8000"
    volumes:
      - "./data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

networks:
  dynamodb-local: {}
