apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-management-service
  labels:
    app: workout-management-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: workout-management-service
  template:
    metadata:
      labels:
        app: workout-management-service
    spec:
      containers:
        - name: workout-management-service
          image: ghcr.io/SamirMarin/workout-management-service:e237236f235f1961411787f3c532696bcccab3c4
          ports:
            - containerPort: 1323
