  name: test

  on:
    push:
      branches:
        - main

    pull_request:
      branches:
        - main

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: set-up go
          uses: actions/setup-go@v5
          with:
            go-version: '1.21'
        - name: test
          run: |
            mkdir -p ./data
            chmod 755 ./data
            docker compose up -d
            echo "sleep"
            sleep 20
            nc -vz localhost 8000
            aws --version
            docker logs dynamodb-local
            aws dynamodb list-tables --region us-west-2 --endpoint-url http://localhost:8000 --debug
          env:
            AWS_ACCESS_KEY_ID: test
            AWS_SECRET_ACCESS_KEY: test
            AWS_DEFAULT_REGION: 'us-west-2'
            DYNAMODB_LOCAL_ENDPOINT: "http://localhost:8000"