  name: test

  on:
    push:
      branches:
        - main

    pull_request:
      branches:
        - main

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: set-up go
          uses: actions/setup-go@v5
          with:
            go-version: '1.21'
        - name: test
          run: |
            docker compose up -d
            until curl --output /dev/null --silent --fail http://127.0.0.1:8000; do
              echo 'Waiting for DynamoDB Local...'
              sleep 20
              curl -v http://127.0.0.1:8000
            done
            ./scripts/dynamodb/create-table.sh
            go test -v ./...
            docker compose down
          env:
            AWS_ACCESS_KEY_ID: test
            AWS_SECRET_ACCESS_KEY: test
            DYNAMODB_LOCAL_ENDPOINT: "http://127.0.0.1:8000"