  name: test

  on:
    push:
      branches:
        - main

    pull_request:
      branches:
        - main

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: set-up go
          uses: actions/setup-go@v5
          with:
            go-version: '1.21'
        - name: test
          run: |
            docker compose up -d
            sleep 20
            ./scripts/dynamodb/create-table.sh
            go test -v ./...
          env:
            AWS_ACCESS_KEY_ID: test
            AWS_SECRET_ACCESS_KEY: test
            AWS_DEFAULT_REGION: 'us-west-2'
            DYNAMODB_LOCAL_ENDPOINT: "http://localhost:8000"
            DOCKER_COMPOSE_COMMAND_OPTS: "-inMemory"