  name: test

  on:
    push:
      branches:
        - main

    pull_request:
      branches:
        - main

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: set-up go
          uses: actions/setup-go@v5
        - name: Run docker compose
          run: docker compose up -d
        - name: Run dynamodb set-up scripts
          run: ./scripts/dynamodb/create-table.sh
          env:
            AWS_ACCESS_KEY_ID: test
            AWS_SECRET_ACCESS_KEY: test
        - name: test
          run: |
            go test -v ./...
          env:
            AWS_ACCESS_KEY_ID: test
            AWS_SECRET_ACCESS_KEY: test