  name: test

  on:
    push:
      branches:
        - main

    pull_request:
      branches:
        - main

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: set-up go
          uses: actions/setup-go@v5
          with:
            go-version: '1.21'
        - name: test
          run: |
            docker compose up -d
            echo "sleep"
            sleep 20 
            aws dynamodb create-table \
              --table-name Workout \
              --attribute-definitions \
              AttributeName=Owner,AttributeType=S \
              AttributeName=Name,AttributeType=S \
              --key-schema \
              AttributeName=Owner,KeyType=HASH \
              AttributeName=Name,KeyType=RANGE \
              --provisioned-throughput \
              ReadCapacityUnits=5,WriteCapacityUnits=5 \
              --table-class STANDARD \
              --region us-west-2 \
              --endpoint-url http://127.0.0.1:8000
            go test -v ./...
            docker compose down
          env:
            AWS_ACCESS_KEY_ID: test
            AWS_SECRET_ACCESS_KEY: test
            AWS_DEFAULT_REGION: 'us-west-2'
            DYNAMODB_LOCAL_ENDPOINT: "http://127.0.0.1:8000"